In [1]:
import numpy as np

In [2]:
d3 = np.arange(50).reshape(2,5,5)

In [3]:
d3[0,2:4,1:3]

array([[11, 12],
       [16, 17]])

In [4]:
d3[1]

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [8]:
#d3[1:2,4:5,0:5]
d3[1:,4:,:]

array([[[45, 46, 47, 48, 49]]])

In [9]:
d3[0:,3:,2:4]

array([[[17, 18],
        [22, 23]],

       [[42, 43],
        [47, 48]]])

In [10]:
d3[0:,2:4,1:3]

array([[[11, 12],
        [16, 17]],

       [[36, 37],
        [41, 42]]])

In [13]:
x = np.array([[1,2,3]])
y = np.array([[1],[2],[3]])

In [15]:
x.shape, y.shape

((1, 3), (3, 1))

In [20]:
x,y = np.broadcast_arrays(x,y) #rows and columns same at x, y

In [17]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [18]:
y

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [19]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [29]:
a = np.array([[1],[2]])
b = np.array([[1,2,3]])

In [30]:
a.shape, b.shape

((2, 1), (1, 3))

In [31]:
a

array([[1],
       [2]])

In [32]:
b

array([[1, 2, 3]])

In [23]:
a,b = np.broadcast_arrays(a,b)

In [24]:
a

array([[1, 1, 1],
       [2, 2, 2]])

In [25]:
b

array([[1, 2, 3],
       [1, 2, 3]])