In [1]:
import numpy as np

In [2]:
arr = np.arange(1,37).reshape(6,6)

In [3]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [4]:
#getting a simple complete row

In [5]:
#arr[row,column]
arr[2:3,0:7]  #2 dimensional

array([[13, 14, 15, 16, 17, 18]])

In [18]:
arr[2,0:]   #similar to upper one   and 1 dimensional

array([13, 14, 15, 16, 17, 18])

In [19]:
arr[2,:]  #also similar   and 1 dimensional

array([13, 14, 15, 16, 17, 18])

In [20]:
arr[2] #similar and 1 dimensional

array([13, 14, 15, 16, 17, 18])

In [21]:
arr[2:3,0:1]

array([[13]])

In [24]:
arr[0,4:5]

array([5])

In [25]:
arr[0:6,4:5]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [26]:
#arr[s:e:step, s:e:step]
arr[:,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [56]:
arr[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [28]:
arr[:,::-2]

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [29]:
arr[::-2,:]

array([[31, 32, 33, 34, 35, 36],
       [19, 20, 21, 22, 23, 24],
       [ 7,  8,  9, 10, 11, 12]])

In [32]:
d3 = np.arange(50).reshape(2,5,5)

In [33]:
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [34]:
#indexing pick 17

In [35]:
d3.shape

(2, 5, 5)

In [36]:
d3[1,3,2]

42

In [37]:
d3[0,4,3]

23

In [41]:
#similar to upper one
d4 = np.arange(60).reshape(2,2,5,3)

In [42]:
d4

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],

        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]],


       [[[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]]])

In [44]:
d3[0][3][1:4]  #slicing

array([16, 17, 18])

In [45]:
d3[0][3][2]

17

In [48]:
d3[1,:,1]   #2nd matrixs, all rows, 1 column

array([26, 31, 36, 41, 46])

In [51]:
d3[0,2,0:5]

array([10, 11, 12, 13, 14])

In [52]:
d3[0][2:3][0:5]

array([[10, 11, 12, 13, 14]])

In [55]:
d3[1][:,1:2]

array([[26],
       [31],
       [36],
       [41],
       [46]])

# Boolean Indexing

In [106]:
data = np.arange(64).reshape(8,8)

In [107]:
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [84]:
bolarr = np.array([False, True, False, False, True, True, False, True], dtype="bool")

In [85]:
bolarr

array([False,  True, False, False,  True,  True, False,  True])

In [86]:
data>50

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [87]:
data[data>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [91]:
data[bolarr]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [83]:
data[[2,1,4,3,0]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [112]:
bolarr = np.array(["ali", "nekal", "hamza", "zia", "waqas", "rayan", "daniyal", "ahmed"])

In [113]:
cond = bolarr == "hamza"
cond

array([False, False,  True, False, False, False, False, False])

In [118]:
cond = (bolarr == "ali") | (bolarr == "rayan")
cond

array([ True, False, False, False, False,  True, False, False])

In [120]:
data[~cond]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [122]:
data[cond]   #full row of index of ali and rayan (0,5)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [40, 41, 42, 43, 44, 45, 46, 47]])

# Fancy Indexing

In [147]:
arr1[2]

NameError: name 'arr1' is not defined

In [148]:
arr1[[7,3,2,0],1:3]]

SyntaxError: invalid syntax (<ipython-input-148-14d304c03771>, line 1)

In [149]:
arr2 = np.arange(16).reshape(4,4)

In [126]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [130]:
arr2[[2,3,0,1],[2,1,0,3]]
#(2,2),(3,1),(0,0),(1,3)

array([10, 13,  0,  7])

In [142]:
arr2[[1,0,3,2]][:,[0,3,1,2]]
#means : (all) and after : this define list in which order you want it
#1[0,3,1,2], 0[0,3,1,2] 3[0,3,1,2], 2[0,3,1,2]

array([[ 4,  7,  5,  6],
       [ 0,  3,  1,  2],
       [12, 15, 13, 14],
       [ 8, 11,  9, 10]])

In [145]:
arr2.T #transpose row to column change karna 

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [150]:
a = [11,22,23,44,22,11]

In [151]:
a

[11, 22, 23, 44, 22, 11]

In [152]:
sett = set(a)

In [153]:
sett  #repeatation & sorting khudi karega set bante we

{11, 22, 23, 44}

In [159]:
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
a2 = np.array([[7,8,9],[10,11,12]])
a2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [168]:
np.concatenate([a1,a2],axis=1)  #1 for horizontal (columns increase)   0 for vertical (rows increase)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [169]:
np.vstack([a1,a2]) #for vertical concatenation

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [170]:
np.hstack([a1,a2]) #for horizontal concatenation

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [171]:
sp = np.arange(36).reshape(6,6)

In [172]:
sp

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [173]:
np.vsplit(sp,3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [174]:
np.vsplit(sp,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]