In [1]:
import numpy as np

In [2]:
oneD = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
oneD

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(oneD)

numpy.ndarray

In [33]:
oneD.ndim   #no of dimensional in array

1

In [44]:
oneD.shape #4 dimensional vector or 1 dimensional tensor (banana example)

(9,)

In [45]:
zeroD = np.array(100)

In [46]:
zeroD.ndim

0

In [47]:
zeroD.shape

()

In [48]:
twoD = np.array([[[100]]])

In [49]:
twoD.ndim

3

In [50]:
twoD.shape

(1, 1, 1)

In [41]:
twoD2 = np.array([[1,2,3,4], [4,3,2,1],[4,5,6,7]])

In [42]:
twoD2.ndim

2

In [43]:
twoD2.shape

(3, 4)

In [53]:
twoD = np.arange(10).reshape(2,5)

In [54]:
twoD

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [79]:
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [80]:
threeD.shape

(2, 3, 3)

In [77]:
threeD = np.arange(100).reshape(4,5,5)  #1st element depth rows & columns 5
# 100 = 4 * 5 *5

In [76]:
threeD

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [86]:
a1 = np.array([[[1,2], [3,4], [5,6], [7,8]],[[1,2], [3,4], [5,6], [7,8]],[[1,2], [3,4], [5,6], [7,8]]])

In [87]:
a1.shape

(3, 4, 2)

In [88]:
a1

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [89]:
a = np.array([1,2,3,4])

In [91]:
a.dtype  #data type 

dtype('int32')

In [92]:
b = np.array([1,2.5,3,4])

In [93]:
b.dtype

dtype('float64')

In [94]:
c = np.array([1.4,2.6,3.2,4.7], dtype = "int32")

In [95]:
c

array([1, 2, 3, 4])

In [100]:
c.dtype

dtype('float64')

In [102]:
c = c.astype("float32")

In [103]:
c.dtype

dtype('float32')

In [104]:
alist = np.arange(10)

In [105]:
alist

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
alist *5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [107]:
blist = np.arange(10).reshape(2,5)

In [108]:
blist

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [109]:
blist *3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [115]:
clist = np.arange(10).reshape(2,5)

In [116]:
blist + clist

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [117]:
t3 = np.arange(9).reshape(3,3)

In [118]:
t3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
t1 = np.arange(6).reshape(2,3)

In [128]:
t1

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
t1.shape, t3.shape

((2, 3), (3, 3))

In [138]:
zeeros = np.zeros((5,5))

In [139]:
zeeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [145]:
eye = np.eye(5,5)

In [146]:
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [147]:
oneLike = np.ones_like(t1)

In [148]:
oneLike

array([[1, 1, 1],
       [1, 1, 1]])

In [149]:
t1 > oneLike

array([[False, False,  True],
       [ True,  True,  True]])

In [152]:
t1>3

array([[False, False, False],
       [False,  True,  True]])

In [153]:
t1

array([[0, 1, 2],
       [3, 4, 5]])

In [155]:
t1[t1>3] #for values  (frame use)

array([4, 5])

In [157]:
t1[t1>oneLike]

array([2, 3, 4, 5])

# Basic Indexing & Silicing

In [158]:
zlist = [1,2,3,4,5,6]

In [159]:
zlist

[1, 2, 3, 4, 5, 6]

In [160]:
zlist[4]

5

In [161]:
type(zlist[5])

int

In [162]:
zlist[1:5]

[2, 3, 4, 5]

In [163]:
type(zlist[1:5]) 

list

In [169]:
TD = np.arange(100).reshape(10,10)

In [171]:
TD

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
TD[5,4] #or TD[5][4]

54

In [168]:
#TD[row[start:end], column[start:end]] 

In [177]:
TD[[5,5], [4,5]]

array([54, 55])

In [179]:
TD[:,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])